"""Quartus Settings File (QSF) manager.

QSF format overview:
  set_global_assignment -name <KEY> <VALUE>
  set_location_assignment <PIN> -to <SIGNAL>
  set_instance_assignment -name <ATTR> <VALUE> -to <SIGNAL>

Design doc reference: Phase 4 — Quartus深度集成
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class PinAssignment:
    signal: str
    pin: str
    io_standard: str = "3.3-V LVTTL"


@dataclass
class QSFProject:
    family:      str = "Cyclone V"
    device:      str = "5CSEBA6U23I7"
    top_entity:  str = ""
    source_files: list[str] = field(default_factory=list)
    pin_assignments: list[PinAssignment] = field(default_factory=list)
    global_assignments: dict[str, str] = field(default_factory=dict)
    timing_constraints: list[str] = field(default_factory=list)   # SDC file paths


# ── Parser ────────────────────────────────────────────────────────────────────

_GLOBAL_RE  = re.compile(r'set_global_assignment\s+-name\s+(\S+)\s+"?([^"\n]+)"?')
_LOCATION_RE = re.compile(r'set_location_assignment\s+(\S+)\s+-to\s+(\S+)')
_IO_STD_RE   = re.compile(r'set_instance_assignment\s+-name\s+IO_STANDARD\s+"([^"]+)"\s+-to\s+(\S+)')


def parse_qsf(path: str) -> QSFProject:
    """Parse an existing .qsf file into a QSFProject."""
    proj = QSFProject()
    pin_io_standards: dict[str, str] = {}

    text = Path(path).read_text(errors="replace")

    for m in _GLOBAL_RE.finditer(text):
        key, val = m.group(1).strip(), m.group(2).strip()
        if key == "FAMILY":
            proj.family = val
        elif key == "DEVICE":
            proj.device = val
        elif key == "TOP_LEVEL_ENTITY":
            proj.top_entity = val
        elif key in ("VERILOG_FILE", "SYSTEMVERILOG_FILE", "VHDL_FILE"):
            proj.source_files.append(val)
        elif key == "SDC_FILE":
            proj.timing_constraints.append(val)
        else:
            proj.global_assignments[key] = val

    for m in _IO_STD_RE.finditer(text):
        pin_io_standards[m.group(2)] = m.group(1)

    for m in _LOCATION_RE.finditer(text):
        pin, signal = m.group(1), m.group(2)
        proj.pin_assignments.append(PinAssignment(
            signal=signal,
            pin=pin,
            io_standard=pin_io_standards.get(signal, "3.3-V LVTTL"),
        ))

    return proj


def generate_qsf(proj: QSFProject) -> str:
    """Render a QSFProject back to QSF text."""
    lines: list[str] = [
        "# Generated by quartus-mcp",
        f'set_global_assignment -name FAMILY "{proj.family}"',
        f'set_global_assignment -name DEVICE {proj.device}',
        f'set_global_assignment -name TOP_LEVEL_ENTITY {proj.top_entity}',
        "",
    ]

    for src in proj.source_files:
        ext = Path(src).suffix.lower()
        key = {
            ".v":   "VERILOG_FILE",
            ".sv":  "SYSTEMVERILOG_FILE",
            ".vhd": "VHDL_FILE",
            ".vhdl": "VHDL_FILE",
        }.get(ext, "VERILOG_FILE")
        lines.append(f"set_global_assignment -name {key} {src}")

    if proj.source_files:
        lines.append("")

    for k, v in proj.global_assignments.items():
        lines.append(f'set_global_assignment -name {k} "{v}"')

    if proj.global_assignments:
        lines.append("")

    for sdc in proj.timing_constraints:
        lines.append(f"set_global_assignment -name SDC_FILE {sdc}")

    if proj.timing_constraints:
        lines.append("")

    for pin in proj.pin_assignments:
        lines.append(f"set_location_assignment {pin.pin} -to {pin.signal}")
        lines.append(
            f'set_instance_assignment -name IO_STANDARD "{pin.io_standard}" -to {pin.signal}'
        )

    return "\n".join(lines) + "\n"


def add_source_file(qsf_path: str, src_path: str) -> str:
    """Add a source file to an existing QSF, return updated content."""
    proj = parse_qsf(qsf_path)
    if src_path not in proj.source_files:
        proj.source_files.append(src_path)
    return generate_qsf(proj)


def set_pin_assignment(qsf_path: str, signal: str, pin: str, io_standard: str = "3.3-V LVTTL") -> str:
    """Set or update a pin assignment, return updated QSF content."""
    proj = parse_qsf(qsf_path)
    # Remove existing assignment for same signal
    proj.pin_assignments = [p for p in proj.pin_assignments if p.signal != signal]
    proj.pin_assignments.append(PinAssignment(signal=signal, pin=pin, io_standard=io_standard))
    return generate_qsf(proj)
